# Generated by Django 5.0.3 on 2024-04-16 20:26

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('premium_story', models.BooleanField(default=False)),
                ('description', models.TextField()),
                ('audience', models.CharField(choices=[('Everyone', 'Everyone'), ('Teen', 'Teens'), ('Adults', 'Adults'), ('Children', 'Children')], max_length=10)),
                ('language', models.CharField(choices=[('English', 'English'), ('Hindi', 'Hindi'), ('Marathi', 'Marathi'), ('Telugu', 'Telugu'), ('Tamil', 'Tamil'), ('Kannada', 'Kannada'), ('Bengali', 'Bengali'), ('Gujarati', 'Gujarati'), ('Odia', 'Odia'), ('Punjabi', 'Punjabi'), ('Malayalam', 'Malayalam')], max_length=10)),
                ('image', models.ImageField(upload_to='stories/story/images/')),
                ('tag', models.CharField(max_length=100)),
                ('date', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.author')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='storys.category')),
            ],
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('part_image', models.ImageField(upload_to='stories/part/images/')),
                ('part_number', models.IntegerField()),
                ('name', models.CharField(default='Untitled', max_length=100)),
                ('text', ckeditor.fields.RichTextField()),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='storys.story')),
            ],
        ),
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liked_at', models.DateTimeField(auto_now_add=True)),
                ('liked_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Like', to='account.author')),
                ('post', models.ManyToManyField(to='storys.story')),
            ],
        ),
        migrations.CreateModel(
            name='CreatePlaylist',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlists', to='account.author')),
                ('story', models.ManyToManyField(to='storys.story')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commented_at', models.DateTimeField(auto_now_add=True)),
                ('comment_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='account.author')),
                ('post', models.ManyToManyField(to='storys.story')),
            ],
        ),
    ]
