# Generated by Django 5.0.3 on 2024-04-05 09:32

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storys', '0002_alter_part_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='text',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
