# Generated by Django 5.0.3 on 2024-04-06 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storys', '0003_alter_part_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='is_premium',
            field=models.BooleanField(default=False),
        ),
    ]
