# Generated by Django 5.0.3 on 2024-04-08 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storys', '0007_alter_story_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, unique=True),
        ),
    ]
