# Generated by Django 5.0.3 on 2024-04-11 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storys', '0008_alter_part_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreatePlaylist',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlists', to='storys.author')),
                ('story', models.ManyToManyField(to='storys.story')),
            ],
        ),
    ]
