# Generated by Django 5.0.3 on 2024-04-12 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storys', '0012_addportfolio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addportfolio',
            name='link',
            field=models.CharField(max_length=100),
        ),
    ]
