# Generated by Django 5.0.3 on 2024-04-12 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storys', '0013_alter_addportfolio_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='premium_story',
            field=models.BooleanField(default=False),
        ),
    ]
